### ISSUE TITLE
Need to be able to use 'sslConnector.SSLCertificateFile'

### ISSUE THREAD

**Issue by xiujunma** [kawansoft/aceql-http#31]
Need to be able to use 'sslConnector.SSLCertificateFile' instead of 'sslConnector.keystoreFile' to enable SSL.

**Comment by ndepomereu** [comment]
Yes, this needs to be fixed.
This will be for sure in the next version (high priority).

**Comment by ndepomereu** [comment]
Fixed with this temporary solution.

While we are finishing the next version, please replace the `aceql-http-12.3.jar` file in your installation with 
the `aceql-http-12.5.jar` file from the upcoming version:

Download Link:
https://download.aceql.com/rest/soft/12.5/download/aceql-http-12.5.jar

Signature:
https://download.aceql.com/rest/soft/12.5/download/aceql-http-12.5.jar.asc
