### ISSUE TITLE
When does aceQL close open DB connections?

### ISSUE THREAD

**Issue by quirrel1002** [kawansoft/aceql-http#8]
Hello,
this is not really a bug, but more a clarification:
currently I am running into the issue that the connections are "used up" during unit testing, and idle DB connections are not closed.
I use the c# client, windows hosted aceQL server and a postgres DB.
Do you have any hint how this is handled or could be influenced?

If you need more info, just let me now.
best regards,
quirrel

**Comment by ndepomereu** [comment]
Hi,



Can you please confirm me :

   1. The config with the AceQL version on server and on client C#  that
   fails.
   2. If you have the technical info and can reproduce, or using your
   memory: the last AceQL version on server that worked correctly.



The code has not been changed on this part, maybe  there was  a change in
the default aceql-server.properties file.



Thanks,

Nicolas





*From:* quirrel1002 <notifications@github.com>
*Sent:* Friday, July 3, 2020 5:06 PM
*To:* kawansoft/aceql-http <aceql-http@noreply.github.com>
*Cc:* Subscribed <subscribed@noreply.github.com>
*Subject:* [kawansoft/aceql-http] When does aceQL close open DB
connections? (#8)



Hello,
this is not really a bug, but more a clarification:
currently I am running into the issue that the connections are "used up"
during unit testing, and idle DB connections are not closed.
I use the c# client, windows hosted aceQL server and a postgres DB.
Do you have any hint how this is handled or could be influenced?

If you need more info, just let me now.
best regards,
quirrel

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kawansoft/aceql-http/issues/8>, or unsubscribe

**Comment by ndepomereu** [comment]
I forgot an important point: make sure the C# client **explicitly** closes the AceQL connection with:
`await connection.CloseAsync();`

Otherwise, using the default configuration, Connections won’t be released in the pool by the server and will be exhausted.
This default behavior can be changed by tuning the Tomcat JDBC polls parameters, I will post an example later.

Nicolas

**Comment by ndepomereu** [comment]
More info about the Tomcat JDBC Pool tuning:

The default AceQL configuration on the server never close `Connections `that have **not** been explicitly closed by remote client users (C#, Java, Python, etc).
This means it is required that the client-side calls a `Connection.close()` (or equivalent in C# and Python) in order to release a remote JDBC `Connection `so that it is put back in the pool and available for other users.

This default behavior may be changed by using two Tomcat JDBC Pool properties: `removeAbandoned `& `removeAbandonedTimeout`.
Add the following lines in your aceql-server.properties (replace `sampledb `by you database name) and `Connections `will be released automatically after the defined timeout:

```
# The removeAbandoned & removeAbandonedTimeout Properties allow to
# remove automatically the abandoned connections so that they 
# are recycled in the pool and will be available for other client users. 
# removeAbandonedTimeout defines the timeout in seconds before the removal.
# These settings are useful in order to avoid connection pool exhaustion 
# when client user programs in C#, Java or Python don't close explicitly 
# their connection.
# Just set removeAbandoned=true for your database and abandoned connections
# will thus be recycled in the connection pool after removeAbandonedTimeout 
# seconds.
# See http://tomcat.apache.org/tomcat-8.5-doc/jdbc-pool.html#Common_Attributes
# for more info and for other important properties.

sampledb.removeAbandoned=true
sampledb.removeAbandonedTimeout=120
```

(Please note that this will have an impact on the behavior of client applications: AeQL Connections will be “cut” after 120 seconds, and a new Connection will then have to be re-created.)

Please note that the `org.kawanfw.sql.api.server.DefaultPoolsInfo` servlet allows to monitor the state of the Tomcat JDBC Pool in order to know how many client users are connected, how many `Connections `are available in the pool, etc.
See the bottom of [aceql-server.properties](https://github.com/kawansoft/aceql-http/blob/master/conf/aceql-server.properties) and the [DefaultPoolsInfo Javadoc ](https://www.aceql.com/rest/soft/5.0.4/javadoc/org/kawanfw/sql/api/server/DefaultPoolsInfo.html) for more info.

**Comment by quirrel1002** [comment]
Thanks for the infos and the hint to the tomcat parameters. I have the  await connection.CloseAsync(); already in tear down methods. I saw the await is missing. I will add this and also the remove Abandoned and report back if there are any issues.

**Comment by quirrel1002** [comment]
I tested today and looks the "issue" is resolved with the removeAbandoned setting as written above. I also investigated and the "not closing" might also come from unit testing in conjuntion with a not ideal Task.Run(()=>connection.CloseAsync()).Result implementation
So, from aceQL view this call can be closed.
